### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dskarasev** [l-zeuch/lagpdb-cc#48] opened 2021-10-02 23:23 UTC
**Describe the bug**
Hi! I have setup the script as described in README and have the same issue #44. 
This error message appears on trying to run -report dbSetup command

Also after adding these scripts to the CC I started to get another error message (please have a look at second screenshot)

Could you please advise what to do. Thanks!

**To Reproduce**
1. Setup script according to README, make setup with proper channel anc cc ids in customReport.gotmpl
2. Open Discord on report-log channel and type -report dbSetup command

**Expected behavior**
✅ Your report-system is now set up!

**Screenshots**
<img width="793" alt="Снимок экрана 2021-10-03 в 02 09 24" src="https://user-images.githubusercontent.com/10157151/135734142-6b638c55-329e-4e69-a30c-e33d761dec52.png">

<img width="790" alt="Снимок экрана 2021-10-03 в 02 20 03" src="https://user-images.githubusercontent.com/10157151/135734191-244b0d0e-55ed-41f1-8ff4-bf70d72456b3.png">

**Additional context**

**Comment by l-zeuch** [comment] 2021-10-02 23:55
Duplicate of #44 which pointed out where to look at.
Closing as invalid.

**Closed by l-zeuch** 2021-10-02 23:55 UTC
